### ISSUE TITLE
Inference network crashes with post-processing

### ISSUE THREAD

**Issue by JMBokhorst** [simongraham/hovernet_inference#37]
Hi, 

I was trying your model out on my own dataset, unfortunately, I ran into a couple of issues. I hope you guys can point me in the right direction: 
- Python crashes with a broken pipe as soon as the network starts post-processing. 
- The network is very slow, it took 12 hours before I got to the post-processing step, is there a way to increase the processing speed (I saw the GPU being only utilized ones every X minutes, but the writing/processing of invalid patches takes a long time). Is it required to write all non-valid patches to memory?
- The mem-files are extremely large, 1 file (of 1 slide) uses more than 400GB. Not sure why though?
- With the new versions MRXS is not supported by default, is there a specific reason why MRXS is removed? 

Thanks in advance, 
Kind regards.

**Comment by simongraham** [comment]
Hi @JMBokhorst ,

Thanks for reaching out. 

Can you please let me know what mode you are using. Is it `tile` or `wsi` mode. Then please provide me with the image dimensions. 

We have implemented a PyTorch version of the code that we will be primarily supporting from now on. Here, you will be able to process tiles and WSIs in the same way that you see in this repository. Please refer to [this repo](https://github.com/vqdang/hover_net) for more information. If you still run into issues when running with the new PyTorch version then we can investigate further. 

With regards to the memory map files - they are typically large because they have the dimensions of the WSI at 40x. These are temporary files that can be removed afterwards. If this becomes a problem, then please post a new issue in the PyTorch repository.

MRXS should be supported because it can be read via openslide, which is what we do. Again, if you still run into problems then please open up an issue in the PyTorch version of the repository.

**Comment by JMBokhorst** [comment]
Hi @simongraham, 

Thanks for the quick response! 

I will check out the new PyTorch repo, to see if the issues are resolved.

I'm trying to process multiple WSI's with roughly an image size of 100k x 200k at 40X, I changed the dtype of the memory map to float16 because for a single file I needed more than 500GB for that image. After changing it to float16 the size was reduced to ~410GB.

I quickly had a peek at the PyTorch version and saw that MRXS is not supported by default in the code (it's not in the supported WSI formats of the wsi-handler). Some minor changes are required to the file-list extractor to make it work correctly (I will make a PR for the PyTorch version).  

The specs of the machine are: 
CPU: i7-7700K (4 core / 8 thread)
MEM: 32GB 
GPU: 2080Ti
500G SSD

**Comment by simongraham** [comment]
Thanks for this info - I will look into the above and include mrxs as a supported file type in the file handler. Please keep me updated as to whether the PyTorch version becomes quicker.

**Comment by simongraham** [comment]
Closing as issue has been moved [here](https://github.com/vqdang/hover_net/issues/79)
