### ISSUE TITLE
Question about instances.npy files

### ISSUE THREAD

**Issue by Noemie-B** [simongraham/hovernet_inference#45]
Hi,
sorry for my question, maybe the answer is obvious.
I used hovernet on slide images and I work on the instances.npy files.  I have numpy ndarray (512*512) and I expected values only between 0 and 5 (the predicted class for the pixel)  but I'm very surprise to see other values such as 17, 147, 300. etc which are different for each patch (I mean patch 1 has ~10 "unexpected" values, patch 2 ~10 others, etc).
Please, can you explain me what I missed ?
Thank you for your help

**Comment by lucas-sancere** [comment]
Hi Noemie, 

I answer as an hovernet user (I am not one of the creator).

The instances.npy is the result of the instance segmentation done by hovernet, not the classification. Then each nucleus will have a different value, because it separates instances (nucleus one will be filled with pixel of value 1 and so on) and not classes.

The output of the classification is, depending on the mode used, the json file and/or the overlay.png file.

**Comment by Noemie-B** [comment]
Hi Lucas,
thank you for your answer. Yes, I used the json file. So if I well understand, it's the "ID" of the nucleus in each pixel ?

Merci ;-)

**Comment by lucas-sancere** [comment]
Hi Noemie,

   Yes it's exactly that. If you don't have further questions about it, you might close the issue. 
   
 De rien :)
